### ISSUE TITLE
Is exo4jax ready for testers?

### ISSUE THREAD

**Issue by vandalt** [exoplanet-dev/jaxoplanet#1]
I recently started playing with JAX and I really like it so far. I wanted to use it to fit exoplanet timeseries (RV + relative astrometry) and saw that this repo exists (via [this Gist](https://gist.github.com/dfm/a67e57a847ab67e825002c0ea4a42155)). I understand this is a work in progress and that `exoplanet` is still the stable option (as discussed here: https://github.com/exoplanet-dev/exoplanet/issues/234#issuecomment-1233267544).

However, I was wondering if this package is mature enough for other users to test it on their projects in your opinion? If so I'd be happy to give it a try and report issues if I encounter any.

Thank you!

**Comment by dfm** [comment]
Thanks for the question! The documentation is still clearly very lacking, but I've been using this package for my research for a while now and I think it should definitely be in good shape for RV + astrometry. (The transit implementation is somewhat novel and less well tested, but also probably fine...)

I'd be very happy for you to play around with it and I'm keen to answer questions and any issues that you find!

One thing is that I definitely want to change the name, but I don't have any good ideas...

**Comment by dfm** [comment]
@catrionamurray Excellent!! We're also doing a bunch of testing for the transit stuff over here so definitely stay in touch!

I ❤️ jaxoplanet...

**Comment by catrionamurray** [comment]
So far so good with testing out the transit fitting!
![exo4jax_wlc](https://user-images.githubusercontent.com/34891147/191110074-d4cfd038-df93-4160-9965-7fe9bb57ce1e.png)

**Comment by benjaminpope** [comment]
Saw this in the ARAA and it looks great... was going to ask the same thing, is it mature enough for us to start playing around with?

**Comment by dfm** [comment]
@benjaminpope — not much has changed since our conversation above: Please do check it out, but YMMV!

**Comment by benjaminpope** [comment]
Good, just checking, half to subscribe for updates ;) Love the new review paper materials. Might talk about it at journal club tomorrow.

**Comment by dfm** [comment]
The current status here is that the docs are still very much a WIP but some of us are using jaxoplanet is production now!
