### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by shashankdholakia** [exoplanet-dev/jaxoplanet#102]
It's been a while since the last release on PyPI and there are a lot of cool new features! Would be great to push a new version there soon.

**Comment by dfm** [comment]
Thanks! We didn't manage to get this released this past week, but we'll aim for the upcoming week as soon as a few of the new PRs get merged!

**Comment by dfm** [comment]
`v0.0.2` is now available on PyPI: https://pypi.org/project/jaxoplanet/
