### ISSUE TITLE
Adding more information to README.md

### ISSUE THREAD

**Issue by soichiro-hattori** [exoplanet-dev/jaxoplanet#122]
The current README.md that's shown on the repo is a bit barebones and I think should be updated. I think the RTD landing page has text we can copy-paste into the README file to give users some more information. 

@lgrcia @jiayindong @catrionamurray @dfm: What else do you all think should be added to it? 
I was thinking some "QuickStart" code and also citation information.

**Comment by dfm** [comment]
I totally agree that the current README isn't sufficient, but I always struggle to figure out the right balance here. In principle, I think that the README should include enough info to get you started, but this also means that we need to maintain two separate versions of the intro docs. One option would be to directly include the README into the docs.

Either way, I think it would be great if you could take a stab at drafting something in a PR, @soichiro-hattori, and we can iterate there.

A possible outline:

1. Statement of need
2. Installation
3. Quick start usage (creating an orbit?)
4. Links to the rest of the docs
5. Citation & license
