### ISSUE TITLE
Default `mass` and  `eccentricity` for `Body`

### ISSUE THREAD

**Issue by lgrcia** [exoplanet-dev/jaxoplanet#128]
When instantiating a `keplerian.Body`, would that be useful to give default values to the `mass` and `eccentricity`? Currently they default to `None`

```python
from jaxoplanet.orbits import keplerian

body = keplerian.Body(radius=0.5, period=1.0)
body
```
```
Body(
  central=Central(
    mass=<Quantity(1.0, 'M_sun')>,
    radius=<Quantity(1.0, 'R_sun')>,
    density=<Quantity(0.238732415, 'M_sun [/](https://file+.vscode-resource.vscode-cdn.net/) R_sun ** 3')>
  ),
  time_ref=<Quantity(-0.25, 'day')>,
  time_transit=<Quantity(0.0, 'day')>,
  period=<Quantity(1.0, 'day')>,
  semimajor=<Quantity(4.208278179168701, 'R_sun')>,
  sin_inclination=<Quantity(1.0, 'dimensionless')>,
  cos_inclination=<Quantity(0.0, 'dimensionless')>,
  impact_param=<Quantity(0.0, 'dimensionless')>,
  mass=None,
  radius=<Quantity(0.5, 'R_sun')>,
  eccentricity=None,
  sin_omega_peri=None,
  cos_omega_peri=None,
  sin_asc_node=None,
  cos_asc_node=None,
  radial_velocity_semiamplitude=None,
  parallax=None
)
```
That would remove some ambiguity when using the object.

If so I can open a PR.

**Comment by dfm** [comment]
I don't think so! In both cases, a value of `None` has different behavior than a value of `0.0`. This is especially obvious for eccentricity: when `eccentricity is None`, the Kepler solver is never called, so the computations will be significantly faster!

**Comment by lgrcia** [comment]
I see. I compared to `starry` when the `Secondary` has a default `mass`, and the rest of the defaults behavior is slightly different. Happy to stick to the current implementation then!
