### ISSUE TITLE
Renaming `SurfaceMapSystem` attributes

### ISSUE THREAD

**Issue by soichiro-hattori** [exoplanet-dev/jaxoplanet#162]
For a `SurfaceMapSystem` instance, the `central` object's surface map is called `surface_map` while the `bodies`' surface maps are called `surface_maps`. Could we rename them to `central_surface_map` and `bodies_surface_maps` for clarity? 

@dfm, @lgrcia: What do you think?

**Comment by lgrcia** [comment]
I think it would work well!

**Comment by dfm** [comment]
Sure - I'd be happy with that!
