### ISSUE TITLE
`KeplerianOrbit` params types casting

### ISSUE THREAD

**Issue by lgrcia** [exoplanet-dev/jaxoplanet#65]
Defining an orbit with `KeplerianOrbit.init` casts all parameters to `float32` although `"jax_enable_x64"` is set to `True`. Is that expected?

Example:
```python
from jax import config
config.update("jax_enable_x64", True)

from jaxoplanet.orbits import KeplerianOrbit

orbit = KeplerianOrbit.init(period=1., radius=1e-4)
orbit.bodies[0].mass.dtype
```
output:
```
dtype('float32')
```

Behaviour is from [orbits/keplerian.py#L71](https://github.com/exoplanet-dev/jaxoplanet/blob/main/src/jaxoplanet/orbits/keplerian.py#L71)

**Comment by dfm** [comment]
The parameters to orbits are no longer type converted, since #61.
